package com.baluga;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableCaching
@MapperScan({
        "com.baluga.module.floodcontrol.mapper",
        "com.baluga.module.index.mapper",
        "com.baluga.module.waterlevel.mapper"
})
public class ChinaHydrologicalMonitoringPlatformApplication {

    public static void main(String[] args) {
        SpringApplication.run(ChinaHydrologicalMonitoringPlatformApplication.class, args);
    }

}
