server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/china_hydrology_monitor
    username: root
    password: Tvgai36183
  data:
    redis:
      host: localhost
      port: 6379
      database: 5
  cache:
    type: redis
    redis:
      time-to-live: 4200000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

amap:
  key: a6d9aeded24e4453798fb33a0a736050
  security-js-code: a6d9aeded24e4453798fb33a0a736050

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.baluga.module.waterlevel.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level:
    com.baluga.module.waterlevel.mapper: DEBUG
